package cxfdemotwo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-04-14T14:04:09.597+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://cxfdemoTwo/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @ResponseWrapper(localName = "sayHiToUserResponse", targetNamespace = "http://cxfdemoTwo/", className = "cxfdemotwo.SayHiToUserResponse")
    @RequestWrapper(localName = "sayHiToUser", targetNamespace = "http://cxfdemoTwo/", className = "cxfdemotwo.SayHiToUser")
    @WebMethod
    public java.lang.String sayHiToUser(
        @WebParam(name = "arg0", targetNamespace = "")
        cxfdemotwo.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://cxfdemoTwo/", className = "cxfdemotwo.GetUsersResponse")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://cxfdemoTwo/", className = "cxfdemotwo.GetUsers")
    @WebMethod
    public cxfdemotwo.IntegerUserMap getUsers();

    @WebResult(name = "return", targetNamespace = "")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://cxfdemoTwo/", className = "cxfdemotwo.SayHiResponse")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://cxfdemoTwo/", className = "cxfdemotwo.SayHi")
    @WebMethod
    public java.lang.String sayHi(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );
}
